### ISSUE TITLE
Just a proposal

### ISSUE THREAD

**Issue by Oevi** [jordiprats/micropython-utelegram#2]
Hi,

before I found your work, I made myself a little telegram bot as a first try with micropython on an esp32. Maybe you could have a look on my suggestion:

Instead of this for-loop in your init:

`for message in messages:`
`  if message['update_id'] > self.message_offset:`
`    self.message_offset = message['update_id']`

you could safe time in case of many messages with:

`self.message_offset = messages[-1]['update_id']`

Greetings from Germany
Oevi

**Comment by jordiprats** [comment]
Hi,
I have [implemented](https://github.com/jordiprats/micropython-utelegram/commit/b613b1550a5c98cd4c37ca535eabbf005c47eb2a) your suggestion with the ability to set the offset so that for stateful applications they can start reading messages at a given  position

thanks,
