### ISSUE TITLE
Bot keeps sending the same message repeatedly in the demo code.

### ISSUE THREAD

**Issue by dimeritium-foil** [jordiprats/micropython-utelegram#5]
Hello, I was trying out the demo code, and the bot keeps receiving the "/ping" command repeatedly and responding accordingly. I didn't have much luck searching for the issue. I'm not sure why it happens.

Thanks in advance.

**Comment by jolitti** [comment]
I'm having the same problem. I think it's because of the offset component in the json request, but i don't know what value should be entered

**Comment by rena2019** [comment]
@jolitti check @dimeritium-foil 's commit at https://github.com/katte/micropython-utelegram/commit/5716b76159009a4ba5b510a6376ef866f7c5336c it works for me
